theme: jekyll-theme-cayman
iconBaseUrl: 'https://unpkg.com/@buddenbrock/typo3-icons@0.2.2/src'

iconsPagetree: {
  'pagetree-page-missing'
}

iconsGrid: {
  'grid-25-25-25-25',
  'grid-33-33-33',
  'grid-25-75',
  'grid-40-60',
  'grid-50-50',
  'grid-60-40',
  'grid-75-25',
  'grid-100',
  'grid-header',
  'grid-header-25-25-25-25',
  'grid-header-33-33-33',
  'grid-header-50-50'
}

iconsContent: {
  'ce-360-degree-player',
  'ce-accordion-1',
  'ce-accordion-2',
  'ce-accordion-3',
  'ce-accordion-4',
  'ce-address',
  'ce-article-1',
  'ce-article-2',
  'ce-article-slider-1',
  'ce-article-slider-2',
  'ce-audio',
  'ce-blockquote-1',
  'ce-blockquote-2',
  'ce-blockquote-3',
  'ce-blockquote-4',
  'ce-blog-preview',
  'ce-book-gallery',
  'ce-book',
  'ce-button-1',
  'ce-button-2',
  'ce-button-icon',
  'ce-calender',
  'ce-chat',
  'ce-comment',
  'ce-contact-1',
  'ce-contact-2',
  'ce-countdown',
  'ce-diagram',
  'ce-download-1',
  'ce-download-2',
  'ce-download-container',
  'ce-employee-1',
  'ce-employee-2',
  'ce-employee-3',
  'ce-filter',
  'ce-form',
  'ce-fundraising',
  'ce-gallery-item',
  'ce-hero-1',
  'ce-hero-2',
  'ce-hero-3',
  'ce-hero-4',
  'ce-hero-5',
  'ce-hero-6',
  'ce-hero-7',
  'ce-icon',
  'ce-iframe',
  'ce-image-1',
  'ce-image-2',
  'ce-image-3',
  'ce-image-4',
  'ce-image-5',
  'ce-image-6',
  'ce-image-7',
  'ce-image-8',
  'ce-image-9',
  'ce-image-downloads',
  'ce-image-slider',
  'ce-image-statement',
  'ce-image-tiles-1',
  'ce-image-tiles-2',
  'ce-image-tiles-3',
  'ce-inline-quote',
  'ce-instagram',
  'ce-lightbox-content',
  'ce-list-1',
  'ce-list-2',
  'ce-listbox',
  'ce-login',
  'ce-map-1',
  'ce-map-2',
  'ce-map-3',
  'ce-media',
  'ce-news',
  'ce-podcast',
  'ce-quote-box',
  'ce-quote-slider',
  'ce-quote',
  'ce-service',
  'ce-shop-search',
  'ce-skills',
  'ce-slider-1',
  'ce-slider-2',
  'ce-social',
  'ce-team-container',
  'ce-team',
  'ce-teaser-1',
  'ce-teaser-2',
  'ce-teaser-box',
  'ce-testimonial',
  'ce-text-1',
  'ce-text-2',
  'ce-text-3',
  'ce-text-4',
  'ce-text-5',
  'ce-text-6',
  'ce-text-box',
  'ce-text-button-1',
  'ce-text-button-2',
  'ce-text-button-3',
  'ce-text-cta',
  'ce-text-highlight',
  'ce-text-image-1',
  'ce-text-image-2',
  'ce-text-image-3',
  'ce-text-image-4',
  'ce-text-image-5',
  'ce-text-image-6',
  'ce-text-image-7',
  'ce-text-image-8',
  'ce-text-image-slider-1',
  'ce-text-image-slider-2',
  'ce-text-list-1',
  'ce-text-list-2',
  'ce-text-video-1',
  'ce-text-video-2',
  'ce-tiles-group-1',
  'ce-tiles-group-2',
  'ce-tiles',
  'ce-vcard-container',
  'ce-vcard',
  'ce-video',
  'ce-webcam'
}

iconsPayment: {
  'payment-amazon-pay',
  'payment-amex',
  'payment-apple-pay',
  'payment-cirrus',
  'payment-diners-club',
  'payment-discover',
  'payment-klarna',
  'payment-maestro',
  'payment-mastercard',
  'payment-patreon',
  'payment-paypal',
  'payment-visa'
}